# Generated by Django 5.0.1 on 2024-02-13 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
        ('mnvoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyllabusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor', models.CharField(max_length=255)),
                ('Opening_hours', models.CharField(max_length=255)),
                ('pusrpose', models.TextField()),
                ('goal', models.TextField()),
                ('overview', models.TextField()),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.lecturemodel')),
            ],
        ),
    ]
