# Generated by Django 5.0.1 on 2024-01-26 05:21

import upload.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='image_file',
            field=models.ImageField(upload_to=upload.models.SavePathImage),
        ),
    ]
